export const vf = (60 * 1000) / 3600; /* 60 kph to m/s */
export const GR = (1 + Math.sqrt(5)) / 2;
export const carLength = 3;
export const carWidth = 1.5;
export const roadWidth = 5;
// export const sj = 4;
// export const kj = (1 / sj) * 1000;
// export const k0 = kj / 3.5;
// export const q0 = vf * k0;
// export const w = q0 / (kj - k0);
export const delta = 0.1;
